export const AICOS = {
  backend: {
    project: 'AICOS',
    sourceOfTruth: 'Supabase',
  },
  routes: {
    admin: '/admin',
    distribution: '/distribution',
    delivery: '/delivery',
    portal: '/portal',
    brain: '/brain',
  },
  tables: {
    prospects: 'prospects',
    clients: 'clients',
    sprints: 'sprints',
    sprintDailyLogs: 'sprint_daily_logs',
    distributionMetrics: 'distribution_metrics',
    deliveryMetrics: 'delivery_metrics',
    distributionProgress: 'distribution_progress',
    deliveryProgress: 'delivery_progress',
    tasks: 'tasks',
    deliverableItems: 'deliverable_items',
    portalMessages: 'portal_messages',
    portalTasks: 'portal_tasks',
    portalDocuments: 'portal_documents',
    sops: 'sops',
    templates: 'templates',
    assets: 'assets',
    financialSnapshots: 'financial_snapshots',
    ledgerEntries: 'ledger_entries',
    campaigns: 'campaigns',
    sprintReports: 'sprint_reports',
    knowledgeDocuments: 'knowledge_documents',
    knowledgeChunks: 'knowledge_chunks',
    knowledgeQueries: 'knowledge_queries',
    approvalLogs: 'approval_logs',
    exceptionLogs: 'exception_logs',
    roleAssignmentHistory: 'role_assignment_history',
    integrationEvents: 'integration_events',
    auditEvents: 'audit_events',
    managerReviews: 'manager_reviews',
    profiles: 'profiles',
  },
  views: {
    opsManagerStatus: 'ops_manager_status',
    proofSprints: 'proof_sprints',
    sprintDailyLog: 'sprint_daily_log',
    monthlyRevenue: 'monthly_revenue',
    ledger: 'ledger',
    distroMetrics: 'distro_metrics',
    appFiles: 'app_files',
    aaDocuments: 'aa_documents',
    aaChunks: 'aa_chunks',
    aaQueries: 'aa_queries',
    clientDeliverables: 'client_deliverables',
  },
} as const

export const CONSOLES = [
  {
    key: 'distribution',
    title: 'Distribution Console',
    route: AICOS.routes.distribution,
    description: 'Prospects, outreach, MJR flow, and acquisition execution.',
    tables: [AICOS.tables.prospects, AICOS.tables.distributionMetrics, AICOS.tables.distributionProgress, AICOS.tables.templates, AICOS.tables.sops],
  },
  {
    key: 'delivery',
    title: 'Delivery Console',
    route: AICOS.routes.delivery,
    description: 'Clients, sprints, delivery metrics, and portal operations.',
    tables: [AICOS.tables.clients, AICOS.tables.sprints, AICOS.tables.deliveryMetrics, AICOS.tables.deliveryProgress, AICOS.tables.portalTasks, AICOS.tables.portalMessages, AICOS.tables.portalDocuments],
  },
  {
    key: 'admin',
    title: 'Admin Console',
    route: AICOS.routes.admin,
    description: 'System status, finance, approvals, exceptions, and governance.',
    tables: [AICOS.views.opsManagerStatus, AICOS.tables.financialSnapshots, AICOS.tables.ledgerEntries, AICOS.tables.approvalLogs, AICOS.tables.exceptionLogs, AICOS.tables.integrationEvents, AICOS.tables.profiles],
  },
  {
    key: 'portal',
    title: 'Client Portal',
    route: AICOS.routes.portal,
    description: 'Client-facing delivery, tasks, messages, and documents.',
    tables: [AICOS.tables.clients, AICOS.tables.sprints, AICOS.tables.portalTasks, AICOS.tables.portalMessages, AICOS.tables.portalDocuments, AICOS.tables.managerReviews],
  },
  {
    key: 'brain',
    title: 'Brain / Knowledge Console',
    route: AICOS.routes.brain,
    description: 'Docs, chunks, queries, templates, SOPs, and assets.',
    tables: [AICOS.tables.knowledgeDocuments, AICOS.tables.knowledgeChunks, AICOS.tables.knowledgeQueries, AICOS.tables.templates, AICOS.tables.sops, AICOS.tables.assets],
  },
] as const
